stages:
    - build
    - deploy

build-job:
    stage: build
    image: docker:27.2.1-dind
    variables:
        DOCKER_IMAGE: aloradesign
    services:
        - docker:27.2.1-dind
    before_script:
        - echo "$CI_REGISTRY_USER"
        - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    script:
        - |
            if [[ "$CI_COMMIT_BRANCH" == "main" ]]; then
              docker build -t "$DOCKER_IMAGE" -f Dockerfile .
            fi

    only:
        refs:
            - main

deploy-job:
    stage: deploy
    image: alpine:latest
    script:
        - apk add docker
        - wget https://github.com/digitalocean/doctl/releases/download/v1.111.0/doctl-1.111.0-linux-amd64.tar.gz
        - tar xf doctl-1.111.0-linux-amd64.tar.gz
        - mv doctl /usr/local/bin
        - |
            if [[ "$CI_COMMIT_BRANCH" == "main" ]]; then
              doctl auth init -t "$ALORA_PRODUCTION_TOKEN"
              doctl registry login		    
              echo "Deploy to production envirement success!"
            fi
    only:
        - main
