stages:
    - build

build-job:
    stage: build
    image: docker:27.2.1-dind
    variables:
        DOCKER_IMAGE: aloradesign
    services:
        - docker:27.2.1-dind
    before_script:
        - echo "$CI_REGISTRY_USER"
        - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    script:
        - |
            if [[ "$CI_COMMIT_BRANCH" == "main" ]]; then
              docker build -t "$DOCKER_IMAGE" -f Dockerfile.production .
            fi

    only:
        refs:
            - main
