stages:
    - build
    - deploy

build-job:
    stage: build
    image: docker:27.2.1-dind
    variables:
        DOCKER_IMAGE: aloradesignimage
    services:
        - docker:27.2.1-dind
    before_script:
        - echo "$CI_REGISTRY_USER"
        - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    script:
        - |
            if [[ "$CI_COMMIT_BRANCH" == "main" ]]; then
              docker build -t "$DOCKER_IMAGE" -f Dockerfile .
            fi

    only:
        refs:
            - main

deploy-job:
    stage: deploy
    image: docker:27.2.1-dind
    services:
        - docker:27.2.1-dind
    script:
        - docker info
        - wget https://github.com/digitalocean/doctl/releases/download/v1.111.0/doctl-1.111.0-linux-amd64.tar.gz
        - tar xf doctl-1.111.0-linux-amd64.tar.gz
        - mv doctl /usr/local/bin
        - |
            if [[ "$CI_COMMIT_BRANCH" == "main" ]]; then
              doctl auth init -t "$ALORA_PRODUCTION_TOKEN"
              echo "----------------------------------------line 36!"
              doctl registry login
              echo "----------------------------------------line 38!"
              docker tag aloradesignimage registry.digitalocean.com/alora-registry/alora-repo
              echo "----------------------------------------line 40!"
              docker push registry.digitalocean.com/alora-registry/alora-repo
              echo "----------------------------------------line 4!"
              doctl apps create-deployment "$ALORA_PROD_APPID" --force-rebuild
              echo "Deploy to production envirement success!"
            fi
    only:
        refs:
            - main
